#!/usr/bin/env bash
# Reclaim disk under $OUTPUT_ROOT without touching anything a running / resumable / final / pending result depends on.
#   dry run (default):  bash scripts/cleanup_outputs.sh          -> lists candidates per rule with sizes
#   delete:             DO_DELETE=1 bash scripts/cleanup_outputs.sh
# Version 3 (2026-10-01, later): + P97 intermediates (report written); feature caches kept only for P35 / P41 references and active P100 / P104.
# P95 intermediates stay until the P104 addendum-2 noisy-J evaluation (reads P95 tau0.3 epochs 100-800) has finished.  Version 2 (2026-10-01).  All rules act only on runs whose status.json says COMPLETED and whose final epoch checkpoint exists, except R5 (smoke dirs).
#   R1  last.pt                      -> deleted (byte-identical to the final epoch_XXX.pt of a COMPLETED run)
#   R2  intermediate epoch_XXX.pt    -> deleted for closed stages (regex DROP_INTER); KEPT for the reference runs and for stages still in use
#   R3  features/ cache              -> deleted for COMPLETED runs except KEEP_FEAT (regenerated by vcs_ssl.evaluate if ever needed)
#   R4  RESUME_TEST_* run dirs       -> deleted
#   R5  finished smoke / gate dirs   -> deleted (evidence lives in slurm_logs, reports/*GATE*, job_ids.json)
# Never touched: RUNNING / STOPPED_BUDGET / FAILED runs, initial.pt, final checkpoints, evaluations/, logs/, status/manifests, configs, reports,
# P45 feature files (T1 / P102), P49 / P57 CLIP features, S2 / S2b solo-learn outputs (P75_S2_solo, P77_S2b_solo: resumed by P99).
set -euo pipefail
OUT=${OUTPUT_ROOT:-/home/infres/yinwang/CS_QMI/outputs}
PY=/home/infres/yinwang/CS_QMI/env/bin/python
# closed stages whose intermediate checkpoints are no longer used (reports written; mechanism records done where planned)
DROP_INTER='^P([5-9]|[12][0-9]|3[0-4]|3[6-9]|4[024]|6[1-9]|87|91|97)_'
# intermediate checkpoints additionally kept inside dropped stages (none) and kept stages: P35 recipe, P41 controls, P43 ceiling, P89 S4, P95 (P96 pending), P97+
KEEP_FEAT='^P(35|41|100|104)_'   # P35 / P41 references (re-probing); P100 / P104 active.  P91 / P95 / P97-P99 caches no longer read (P98 done)
list=$(mktemp); tag=$(mktemp)
add() { echo "$2" >> "$list"; echo "$1" >> "$tag"; }
for d in "$OUT"/*/; do
  run=$(basename "$d")
  if [[ "$run" == RESUME_TEST_* ]]; then add R4 "$d"; continue; fi
  if [[ "$run" =~ ^(smoke_|det_vcs_|SMOKE_|P75_S2_smoke_|P98_P101_smoke_|P85_gate_) ]]; then add R5 "$d"; continue; fi
  [ -f "$d/status.json" ] || continue
  read -r status ep < <("$PY" -c "import json;s=json.load(open('$d/status.json'));print(s.get('status'), s.get('completed_epoch'))" 2>/dev/null || echo "NONE NONE")
  [ "$status" = "COMPLETED" ] || continue
  [[ "$ep" =~ ^[0-9]+$ ]] || continue
  final=$(printf "%s/checkpoints/epoch_%03d.pt" "$d" "$ep")
  [ -f "$final" ] || continue
  [ -f "$d/checkpoints/last.pt" ] && add R1 "$d/checkpoints/last.pt"
  if [[ "$run" =~ $DROP_INTER ]]; then
    for c in "$d"/checkpoints/epoch_*.pt; do [ -e "$c" ] && [ "$c" != "$final" ] && add R2 "$c"; done
  fi
  if [ -d "$d/features" ] && ! [[ "$run" =~ $KEEP_FEAT ]]; then add R3 "$d/features"; fi
done
paste -d' ' "$tag" "$list" > "$list.tagged"
for r in R1 R2 R3 R4 R5; do
  files=$(awk -v r=$r '$1==r{print $2}' "$list.tagged")
  n=$(printf "%s\n" "$files" | grep -c . || true)
  s=$( [ "$n" -gt 0 ] && du -shc $files 2>/dev/null | tail -1 | cut -f1 || echo 0)
  printf "%s  %5d paths  %s\n" "$r" "$n" "$s"
done
echo "total: $(du -shc $(cat "$list") 2>/dev/null | tail -1 | cut -f1)"
if [ "${DO_DELETE:-0}" = "1" ]; then
  xargs -a "$list" rm -rf --; echo "deleted."
else
  echo "(dry run; full list: $list.tagged; re-run with DO_DELETE=1 to delete)"
fi
